## Simplified workflow for deployment testing
name: Dance Magic Dance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  deployments: write

jobs:
  generate:
    runs-on: [ self-hosted ]
    steps:
      - name: Babe with the power
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GOBLINS_ID=$(curl \
              --silent \
              --fail-with-body \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/deployments \
              -d '{"ref":"main","description":"curl: First created, last updated","environment":"goblins","required_contexts":[]}' \
              | jq '.id'
          )
          curl \
              --silent \
              --fail-with-body \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/deployments/$GOBLINS_ID/statuses \
              -d '{"state":"success"}'
